/// Flutter icons MyArrows
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyArrows
///      fonts:
///       - asset: fonts/MyArrows.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyArrows {
  MyArrows._();

  static const _kFontFam = 'MyArrows';

  static const IconData arrow_from = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData arrow_to = const IconData(0xe801, fontFamily: _kFontFam);
}
