/// Flutter icons MyIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData departure = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData metro = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData arrival = const IconData(0xe802, fontFamily: _kFontFam);
}
