/// Flutter icons MyTypes
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyTypes
///      fonts:
///       - asset: fonts/MyTypes.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyTypes {
  MyTypes._();

  static const _kFontFam = 'MyTypes';

  static const IconData comfort_black = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData comfort_deselected = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData d2_deselected = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData d2_selected = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData d3_deselected = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData d3_selected = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData express_deselected = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData express_selected = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData standart_deselected = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData standart_selected = const IconData(0xe809, fontFamily: _kFontFam);
}
