/// Flutter icons MyTransit
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyTransit
///      fonts:
///       - asset: fonts/MyTransit.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyTransit {
  MyTransit._();

  static const _kFontFam = 'MyTransit';

  static const IconData m1 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData m5 = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData m9 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData m10 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData m14 = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData d2 = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData d3 = const IconData(0xe80e, fontFamily: _kFontFam);
}
